DemoApl/Models/Navbar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FileHelpers;

namespace DemoApl.Models
{
    public class Navbar
    {
        public int Id { get; set; }
        public string nameOption { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string area { get; set; }
        public string imageClass { get; set; }
        public string activeli { get; set; }
        public bool status { get; set; }
        public int parentId { get; set; }
        public bool isParent { get; set; }
    }

    [DelimitedRecord("|")]
    public partial class UserData
    {
        public string sName { get; set; }
        public string sFirstName { get; set; }
        public string sUserName { get; set; }
        public string sUserPass { get; set; }
        public string sUserMail { get; set; }
    }
   
}

DemoApl/Models/ViewModels/SingleShotPasswordViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace DemoApl.Models.ViewModels
{
    public class SingleShotPasswordViewModels
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Single Shot Password")]
        public string sUserSingleShotPass { get; set; }
    }
}

DemoApl/Models/ViewModels/UserViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using FileHelpers;

namespace DemoApl.Models.ViewModels
{
    
    public class UserViewLoginModel
    {

        private UserData CtcsConn = new UserData();

        [Required]
        [Display(Name = "User name")]
        public string sUserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string sUserPass { get; set; }

        public UserData IsUserValid(string _username, string _password)
        {
            var engine = new FileHelperEngine<UserData>();
            
            var result = engine.ReadFile(System.Web.HttpContext.Current.Request.MapPath("~\\DbFiles\\FileIn.txt"));

            UserData oUser = result.FirstOrDefault(user => user.sUserName == _username && user.sUserPass == _password);

            return oUser;

        }

    }

    public class LoggedUser
    {
        [Display(Name = "User name : ")]
        public string sName { get; set; }
        [Display(Name = "User first name : ")]
        public string sFirstName { get; set; }
        public string sUserName { get; set; }
        public string sUserPass { get; set; }
        public string sUserMail { get; set; }
        public string sSingleShotPass { get; set; }
    }
}

DemoApl/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DemoApl.Models;
using DemoApl.Models.ViewModels;
using DemoApl.DomainFuncs;

namespace DemoApl.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Login()
        {
            return View("Login");
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult LoginWithPass()
        {
            return View();
        }

        public ActionResult WelcomePage()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(Models.ViewModels.UserViewLoginModel user)
        {
            if (ModelState.IsValid)
            {
                //UserData oUser = DemoApp.Models.UserData.Equals();
                var dbStaff = user.IsUserValid(user.sUserName, user.sUserPass);

                if (dbStaff != null)
                {
                    var iLoggedUser = new LoggedUser();

                    FormsAuthentication.SetAuthCookie(user.sUserName, true);

                    iLoggedUser.sFirstName = dbStaff.sUserName;
                    iLoggedUser.sName = dbStaff.sName;
                    iLoggedUser.sUserName = dbStaff.sUserName;
                    iLoggedUser.sUserPass = dbStaff.sUserPass;
                    iLoggedUser.sUserMail = dbStaff.sUserMail;

                    var sPassword = DemoApl.DomainFuncs.SingleShotPasswordGen.Generate(8, 10);
                    iLoggedUser.sSingleShotPass = sPassword;

                    //var mailService = new GmailService();
                    GmailService.GmailUsername = "some@gmail.com";
                    GmailService.GmailPassword = "somepass";
                    

                    GmailService mailService = new GmailService();
                    mailService.ToEmail = dbStaff.sUserMail;
                    mailService.Subject = "DemoApp auth message";
                    mailService.Body = "Authorization password : " + sPassword;
                    mailService.IsHtml = true;
                    mailService.Send();


                    var dtPassTime = DateTime.Now;
                    Session["User"] = iLoggedUser;
                    Session["PassDateTime"] = dtPassTime;

                    return RedirectToAction("LoginWithPass", "Home");
                    
                }
                
            }

            ModelState.AddModelError("", "The user name or password provided is incorrect.");
            return View(user);

        }

        [HttpPost]
        public ActionResult LoginWithPass(Models.ViewModels.SingleShotPasswordViewModels userLogPass)
        {
            if (ModelState.IsValid)
            {

                var user = Session["User"] as LoggedUser;

                if (((DateTime)Session["PassDateTime"]).AddMinutes(1) < DateTime.Now)
                {
                    ModelState.AddModelError("", "Provided password expired.");
                    return View(userLogPass);
                }

                if (string.Equals(user.sSingleShotPass, userLogPass.sUserSingleShotPass, StringComparison.Ordinal) != true)
                {
                    ModelState.AddModelError("", "Provided is incorrect.");
                    return View(userLogPass);
                                        
                }

                return RedirectToAction("WelcomePage", "Home");

            }

            ModelState.AddModelError("", "Invalid data.");
            return View(userLogPass);
            
            
        }

    }
}

DemoApl/Controllers/NavbarController.cs
using DemoApl.DomainFuncs;
using DemoApl.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoApl.Controllers
{
    public class NavbarController : Controller
    {
        // GET: Navbar
        public ActionResult Index()
        {
            var data = new Data();
            return PartialView("_Navbar", data.navbarItems().ToList());
        }
    }
}

DemoApl/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Index page</h1>
    </div>
</div>


<script src="@Url.Content("~/bower_components/morrisjs/morris.min.js")"></script>
<script src="@Url.Content("~/Scripts/morris-data.js")"></script>

DemoApl/Views/Home/Login.cshtml
@model DemoApl.Models.ViewModels.UserViewLoginModel

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-4 col-md-offset-3">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()          // this is for prevent CSRF attack
                @Html.ValidationSummary(true)

                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Please Sign In</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <fieldset>
                                <div class="form-group">
                                    @Html.LabelFor(Model => Model.sUserName)
                                    @Html.ValidationMessageFor(model => model.sUserName)
                                    <input id="UserLoginId" class="form-control" placeholder="User ID" name="sUserName" type="text" autofocus>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(Model => Model.sUserPass)
                                    @Html.ValidationMessageFor(Model => Model.sUserPass)
                                    <input class="form-control" placeholder="Password" name="sUserPass" type="password" value="">
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                <input type="submit" class="btn btn-lg btn-success btn-block" value="Login" />
                            </fieldset>
                        </form>
                    </div>
                </div>

            }
        </div>
    </div>
</div>

DemoApl/Views/Home/LoginWithPass.cshtml
@model DemoApl.Models.ViewModels.SingleShotPasswordViewModels

@{
    ViewBag.Title = "LoginWithPass";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login With Single Shot Password</h2>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-4 col-md-offset-3">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()          // this is for prevent CSRF attack
                @Html.ValidationSummary(true)

                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Verification</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <fieldset>
                                <div class="form-group">
                                    @Html.LabelFor(model => Model.sUserSingleShotPass)
                                    @Html.ValidationMessageFor(Model => Model.sUserSingleShotPass)
                                    <input class="form-control" placeholder="Password" name="sUserSingleShotPass" type="password" value="">
                                </div>
                                
                                <input type="submit" class="btn btn-lg btn-success btn-block" value="Login" />
                            </fieldset>
                        </form>
                    </div>
                </div>

            }
        </div>
    </div>
</div>

DemoApl/Views/Home/WelcomePage.cshtml
@model DemoApl.Models.ViewModels.LoggedUser

@{
    ViewBag.Title = "WelcomePage";
}

<h2>Welcome</h2>

<div>
    @{
        var LoggedInUser = (DemoApl.Models.ViewModels.LoggedUser)Session["User"];
    }
    <h4>Active User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.sName)
        </dt>

        <dd>
            @LoggedInUser.sName
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sFirstName)
        </dt>

        <dd>
            @LoggedInUser.sFirstName
        </dd>

    </dl>
</div>

DemoApl/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Demo MVC APP</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/bower_components/datatables-responsive/css/dataTables.responsive.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/bower_components/morrisjs/morris.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/bower_components/font-awesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" />

    @Scripts.Render("~/bundles/jquery")
    <script src="@Url.Content("~/bower_components/jquery/dist/jquery.min.js")"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="@Url.Content("~/bower_components/metisMenu/dist/metisMenu.min.js")"></script>

</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        @Html.Action("Index", "Navbar")
        
        <div id="page-wrapper">
            @RenderBody()          
        </div>
    </div>
         
    <script src="@Url.Content("~/bower_components/raphael/raphael-min.js")"></script> 
    <script src="@Url.Content("~/bower_components/datatables/media/js/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Scripts/demo_apl.js")"></script>

    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

DemoApl/Views/Shared/_Navbar.cshtml
@model IEnumerable<DemoApl.Models.Navbar>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        @Html.ActionLink("Demo Application", "Index", new { controller = "Home" }, new { @class = "navbar-brand" })
    </div>
    
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                    @foreach (var item in Model)
                    {
                        if (item.isParent == false && item.parentId == 0)
                        {
                            <li><a href="@Url.Action(item.action, item.controller)"><i class="@item.imageClass"></i> @item.nameOption</a></li>
                        }
                        else
                        {
                            if (item.isParent == true)
                            {
                                <li>
                                    <a href="#"><i class="@item.imageClass"></i> @item.nameOption<span class="fa arrow"></span></a>
                                    <ul class="nav nav-second-level">
                                        @foreach (var child in Model.Where(p => p.parentId == item.Id))
                                        {
                                            if (child.controller == null)
                                            {
                                                <li><a href="#">@child.nameOption</a></li>
                                            }
                                            else
                                            {
                                            <li><a href="@Url.Action(child.action, child.controller)">@child.nameOption</a></li>
                                            }
                                        }
                                    </ul>
                                </li>
                            }
                        }
                    }
                </ul>
            </div>
        </div>
    </nav>